CSS fixes for mobile UI
lpatmo/musical-wordle pull request #104
Opened 2023-06-13 03:24 UTC by lpatmo

## Description
This PR resolves #103

2023-06-13 05:55 UTC, arturolei approved these changes
Looks good to me. Hopefully `rem` resolves some issues.

2023-06-13 22:30 UTC, ISPOL requested changes
Minor issue—the music note on the submit button looks like it's misaligned vertically. Otherwise looks fine.

2023-06-14 00:06 UTC, lpatmo commented
@ISPOL Good call! Fixed.

2023-06-14 00:08 UTC, ISPOL approved these changes

2023-06-14 03:55 UTC, merged